name: Get Life
on:
  schedule:
    # Runs at midnight everyday
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      
      - name: Install dependencies
        run: npm install

      - name: Run script to update README.md
        run: node index.js

      - name: Commit and push changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT}}
        run: |
          git config --global user.name "Arnav-Kadu"
          git config --global user.email "arnavkadoo@gmail.com"
          git add README.md
          git commit -m "New meme added"
          git push
